# Generated by Django 5.1.5 on 2025-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chais/'),
        ),
    ]
